name = "wavepitch-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Bind your Worker to a custom domain (optional)
# routes = [
#   { pattern = "api.wavepitch.com/*", zone_name = "wavepitch.com" }
# ]

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "production"

# Secrets will be added via CLI:
# wrangler secret put CLERK_PUBLISHABLE_KEY
# wrangler secret put CLERK_SECRET_KEY
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY